Ext.regStore("People", {
    model: "Person", 
    data: [
            {id: 1,
            "zipCode": "00001",
            "secondaryCategoryId": 2,
            "secondaryCategoryName":"Directors",
            "city":"Denver",
            "primaryCategoryId":1,
            "primaryCategoryName":"Crew",
            "phoneNumber":"303-555-0001",
            "companyName":"Super Awesome Production, Inc.",
            "emailAddress":"test@test.com",
            "primaryName":"Test Testerton",
            "lastName":"Tersterton",
            "description":"For nearly 10 years, Super Awesome Production has been doing super awesome productions!"},
            {id: 2,
            "zipCode": "00001",
            "secondaryCategoryId": 2,
            "secondaryCategoryName":"Directors",
            "city":"Denver",
            "primaryCategoryId":1,
            "primaryCategoryName":"Crew",
            "phoneNumber":"303-555-0002",
            "companyName":"Happy Gilmore Directors",
            "emailAddress":"test@test.com",
            "primaryName":"Happy Gilmore",
            "lastName":"Gilmore",
            "description":"Not only a great director, but also an oustanding golfer!"},
            {id: 3,
            "zipCode": "00002",
            "secondaryCategoryId": 11,
            "secondaryCategoryName":"Walkie Talkies",
            "city":"Thornton",
            "primaryCategoryId":1,
            "primaryCategoryName":"Crew",
            "phoneNumber":"303-555-0003",
            "companyName":"Clearwire Walkie-Talkies",
            "emailAddress":"test@test.com",
            "primaryName":"",
            "lastName":"Clearwire",
            "description":"Providing the finest Walkie-Talkies ever made!"},
            {id: 4,
            "zipCode": "00002",
            "secondaryCategoryId": 5,
            "secondaryCategoryName":"Craft Services",
            "city":"Denver",
            "primaryCategoryId":3,
            "primaryCategoryName":"Producers",
            "phoneNumber":"303-555-0004",
            "companyName":"Makin' Money Productions",
            "emailAddress":"test@test.com",
            "primaryName":"",
            "lastName":"Money",
            "description":"Making money. Making it rain. That's our thing, ya'll."}
            
        ]
});